# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Homer Multitext project editors' group
tagline:          'Editing manuscripts of the Iliad'
description:      ''
baseurl: 'http://hmteditors.github.io/'



author:
  name:           'Neel Smith'
 
paginate:         5

links:
  - title: HMT home page
    url: http://www.homermultitext.org/
    external: true
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: Github source for this site
    url: https://github.com/homermultitext/hmteditors.github.io
    external: true

   